#!/bin/bash

export PROJ_BASE_DIR=$PWD
export GAZEBO_PLUGIN_PATH=$PROJ_BASE_DIR/build/devel/lib:$GAZEBO_PLUGIN_PATH
export GAZEBO_MODEL_PATH=$PROJ_BASE_DIR/models:$GAZEBO_MODEL_PATH
export GAZEBO_RESOURCE_PATH=$PROJ_BASE_DIR/worlds:$GAZEBO_RESOURCE_PATH
